title: Stuy Fission
email: stuyfission@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First Tech Challenge Team Stuy Fission 310 from Stuyvesant High School

include: ['_pages']
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

instagram_username: stuyfission
facebook_username:  stuyfission
github_username:    fission310

sass:
  style: compressed

disqus:
  shortname: stuyfission
